[phases.setup]
nixPkgs = ["maven", "openjdk17"]

[phases.install]
cmds = ["mvn clean install -DskipTests"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "if [ -f target/agriculture-backend-0.0.1-SNAPSHOT.jar ]; then java -jar target/agriculture-backend-0.0.1-SNAPSHOT.jar --server.port=$PORT; else echo 'JAR file not found, building...'; mvn clean package -DskipTests && java -jar target/agriculture-backend-0.0.1-SNAPSHOT.jar --server.port=$PORT; fi"
