[phases.setup]
nixPkgs = ["maven", "openjdk17"]

[phases.install]
cmds = ["mvn clean install -DskipTests"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -jar target/agriculture-backend-0.0.1-SNAPSHOT.jar"
