[phases.setup]
nixPkgs = ["maven", "openjdk17"]

[phases.install]
cmds = ["mvn clean install -DskipTests"]

[phases.build]
cmds = ["mvn clean package -DskipTests", "echo 'Build completed, checking JAR file...'", "ls -la target/", "find target/ -name '*.jar' -type f", "if [ ! -f target/agriculture-backend-0.0.1-SNAPSHOT.jar ]; then echo 'ERROR: JAR file not created!'; exit 1; else echo 'SUCCESS: JAR file created successfully'; fi"]

[start]
cmd = "java -jar target/agriculture-backend-0.0.1-SNAPSHOT.jar --server.port=$PORT"
